LCA = """
SELECT *,
  CASE WHEN WAGE_UNIT_OF_PAY='Year' THEN WAGE_RATE_OF_PAY_FROM ELSE WAGE_RATE_OF_PAY_FROM*50000 END AS ANNUAL_INCOME,
  '{file_source}' AS FILE_SOURCE,
  UPPER(WORKSITE_COUNTY) AS WORKSITE_COUNTY_UPPER
FROM {view} 
WHERE CASE_STATUS='Certified' 
  AND FULL_TIME_POSITION='Y'
  AND WAGE_UNIT_OF_PAY in ('Year', 'Hour')
"""

PW = """
SELECT *,
  '{file_source}' AS FILE_SOURCE,
  UPPER(PRIMARY_WORKSITE_COUNTY) AS WORKSITE_COUNTY_UPPER
FROM {view}
WHERE CASE_STATUS='Determination Issued'
  AND EMPLOYER_COUNTRY='UNITED STATES OF AMERICA'
"""
